version: "1"

services:

  godzilla-messagebus:
    container_name: godzilla-messagebus
    networks:
      - godzilla
    restart: always
    image: hub.docker.com/nats:latest
    ports:
      - 5101: 4222
      - 5102: 6222
      - 5103: 8222

  godzilla-sql:
    container_name: godzilla-sql
    networks:
      - godzilla
    restarts: always
    image: hub.docker.com/service-godzilla-sql:0.0.1
    ports:
      - 5002: 8085

  godzilla-stock-trader:
    container_name: godzilla-stock-trader
    networks:
      - godzilla
    restarts: always
    image: hub.docker.com/godzilla-stock-trader:0.0.1
    ports:
      - 5002: 8085
    depends_on:
      - godzilla-messagebus
      - godzilla-sql
    environment:
      env: dev
      config_file: config

  godzilla-big-file:
    container_name: godzilla-big-file
    networks:
      - godzilla
    restarts: always
    image: hub.docker.com/godzilla-big-file:0.0.1
    ports:
      - 5002: 8085
    depends_on:
      - godzilla-sql
    environment:
      env: dev
      config_file: config

# Add any volumes here if required
volumes:
  godzilla-sql:

networks:
  godzilla:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 255.255.255.0
