version: "2"

services:

  godzilla-messagebus:
    container_name: godzilla-messagebus
    networks:
      - godzilla
    restart: always
    image: docker.io/nats:latest
    ports:
      - 5101:4222
      - 5102:6222
      - 5103:8222

  godzilla-simulator-stock:
    container_name: godzilla-simulator-stock
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/simulator-stock:0.0.2
    ports:
      - 5104:8085
    depends_on:
      - godzilla-messagebus
    environment:
      natsHost: godzilla-messagebus
      natsPort: 4222

  godzilla-service-stock-trader:
    container_name: godzilla-service-stock-trader
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/service-stock-trader:0.0.1
    ports:
      - 5105:8085
      - 5106:8086
    depends_on:
      - godzilla-messagebus
    environment:
      dbUser: postgres
      dbPassword: admin
      dbName: godzilla

  godzilla-service-mongo-engine:
    container_name: godzilla-service-mongo-engine
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/ap0001_mongo_engine:00.00.07
    ports:
      - 5107:8085
    environment:
      mongoHostAndPort: 192.168.202.108:27017

  # godzilla-sql:
  #   container_name: godzilla-sql
  #   networks:
  #     - godzilla
  #   restart:always
  #   image: docker.io/vickeyshrestha/service-godzilla-sql:0.0.1
  #   ports:
  #     - 5005:8085

  # godzilla-big-file:
  #   container_name: godzilla-big-file
  #   networks:
  #     - godzilla
  #   restarts: always
  #   image: docker.io/vickeyshrestha/godzilla-big-file:0.0.1
  #   ports:
  #     - 5007: 8085
  #   depends_on:
  #     - godzilla-sql
  #   environment:
  #     env: dev
  #     config_file: config

# Add any volumes here if required
volumes:
  godzilla-sql:

networks:
  godzilla:
    driver: "bridge"
      #ipam:
      # driver: default
    #config:
    # - subnet: 10.75.0.0/23
