version: "2"

services:

  godzilla-core-messagebus:
    container_name: godzilla-core-messagebus
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/nats:1.0.0
    ports:
      - 5101:4222
      - 5102:6222
      - 5103:8222

  godzilla-core-postgres:
    container_name: godzilla-core-postgres
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/postgres:1.0.0
    ports:
      - 5104:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: godzilla

  godzilla-core-mongo:
    container_name: godzilla-core-mongo
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/mongo:1.0.0
    ports:
      - 5105:27017

  godzilla-simulator-stock:
    container_name: godzilla-simulator-stock
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/simulator-stock:0.0.2
    ports:
      - 5111:8085
    depends_on:
      - godzilla-core-messagebus
    environment:
      natsHost: godzilla-core-messagebus
      natsPort: 4222

  godzilla-service-stock-trader:
    container_name: godzilla-service-stock-trader
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/service-stock-trader:0.0.3
    ports:
      - 5112:8085
      - 5113:8086
    depends_on:
      - godzilla-core-messagebus
      - godzilla-core-postgres
    environment:
      dbUser: postgres
      dbPassword: admin
      dbName: godzilla
      dbHost: godzilla-core-postgres
      dbPort: 5432
      natsUrl: godzilla-core-messagebus:4222

  godzilla-service-mongo-engine:
    container_name: godzilla-service-mongo-engine
    networks:
      - godzilla
    restart: always
    image: docker.io/vickeyshrestha/ap0001_mongo_engine:00.00.07
    ports:
      - 5114:8085
    depends_on:
      - godzilla-core-mongo
    environment:
      mongoHostAndPort: godzilla-core-mongo:27017

  # godzilla-big-file:
  #   container_name: godzilla-big-file
  #   networks:
  #     - godzilla
  #   restarts: always
  #   image: docker.io/vickeyshrestha/godzilla-big-file:0.0.1
  #   ports:
  #     - 5007: 8085
  #   depends_on:
  #     - godzilla-sql
  #   environment:
  #     env: dev
  #     config_file: config

# Add any volumes here if required
volumes:
  godzilla-sql:

networks:
  godzilla:
    driver: "bridge"
      #ipam:
      # driver: default
    #config:
    # - subnet: 10.75.0.0/23
